import assert from "node:assert/strict";
import test from "node:test";
import { WechatOfficialApiExecutor } from "../packages/platforms/wechat-executor.mjs";
import { SelectorRegistry } from "../packages/platforms/selector-registry.mjs";
import { AuthorizationAcceptance } from "../packages/platforms/authorization.mjs";
import { getOfficialRuleSet, preflightPublishContent, registerOfficialRuleSet } from "../packages/publish-engine/content-preflight.ts";

test("WeChat official executor creates a draft, submits it, and resolves the public URL", async () => {
  const calls = []; const fetcher = async (url) => { const value = String(url); calls.push(value); if (value.includes("/draft/add")) return new Response(JSON.stringify({ media_id: "draft-media" }), { status: 200 }); if (value.includes("/freepublish/submit")) return new Response(JSON.stringify({ publish_id: "publish-1" }), { status: 200 }); if (value.includes("/freepublish/get")) return new Response(JSON.stringify({ publish_status: 0, article_detail: { item: [{ article_url: "https://mp.weixin.qq.com/s/example" }] } }), { status: 200 }); throw new Error(value); };
  const executor = new WechatOfficialApiExecutor({ accessToken: "test-token", fetch: fetcher, apiBase: "https://api.weixin.qq.com" }); const result = await executor.publish({ jobId: "job", idempotencyKey: "key", title: "Title", markdown: "<p>Body</p>", assets: [{ role: "cover", source: { type: "platform_media", mediaId: "cover-media" } }] });
  assert.equal(result.ok, true); assert.equal(result.publicUrl, "https://mp.weixin.qq.com/s/example"); assert.equal(result.platformDraftId, "draft-media"); assert.equal(calls.length, 3);
});

test("selector registry versions bundles and detects platform structure changes", () => { const registry = new SelectorRegistry(); registry.register({ schemaVersion: 1, platform: "test", version: "2026.1", selectors: { publishButton: { name: "publish", selector: "button.publish", required: true } } }); assert.equal(registry.detectStructureChange("test", { publish: true }).changed, false); const changed = registry.detectStructureChange("test", {}); assert.equal(changed.changed, true); assert.deepEqual(changed.missing, ["publishButton"]); });
test("live executor requires explicit human authorization acceptance", () => { const acceptance = new AuthorizationAcceptance(); assert.throws(() => acceptance.assertAccepted({ platform: "test", accepted: false })); assert.equal(acceptance.assertAccepted({ platform: "test", accepted: true, acceptedBy: "operator", acceptedAt: new Date().toISOString() }), true); });
test("official rule bundles are versioned, sourced, and never impose editorial preferences", () => { registerOfficialRuleSet({ platform: "rules-test", version: "1.0.0", effectiveAt: "2026-01-01", coverage: "verified", note: "Objective platform field requirement.", sources: [{ title: "Official docs", url: "https://platform.example.test/docs", publisher: "Platform", reviewedAt: "2026-01-02" }], validate(input) { return input.categoryId ? {} : { blockers: [{ code: "category_required", message: "Category is required by the platform.", scope: "official_platform_rule", sourceUrl: this.sources[0].url }] }; } }); const result = preflightPublishContent({ platform: "rules-test", title: "Short", markdown: "Link https://example.test" }); assert.equal(result.ruleVersion, "1.0.0"); assert.equal(result.passed, false); assert.equal(result.blockers[0].code, "category_required"); assert.equal(getOfficialRuleSet("rules-test").sources[0].publisher, "Platform"); assert.equal(result.warnings.some((item) => /length|promotion|technical|link count/i.test(item.code)), false); });
