import type { AuthStatus, PublishResult, VerifyResult } from "./adapter-types.js";
import type { PlatformPublishPayload, PublishPlatformKey } from "./types.js";

export interface FormalPublishTransport { checkAuth(platform: PublishPlatformKey): Promise<AuthStatus>; publish(platform: PublishPlatformKey, payload: PlatformPublishPayload): Promise<PublishResult>; verify(platform: PublishPlatformKey, result: PublishResult): Promise<VerifyResult>; }

function bridgeUrl() { return process.env.PUBLISH_BRIDGE_URL || "http://127.0.0.1:9528"; }
function local(value: string) { try { return ["localhost", "127.0.0.1", "::1", "[::1]", "host.docker.internal"].includes(new URL(value).hostname); } catch { return false; } }

export class BridgeTransport implements FormalPublishTransport {
  constructor(private readonly fetcher: typeof fetch = fetch) {}
  private async request(path: string, body: unknown) {
    if (!local(bridgeUrl())) throw new Error("PUBLISH_BRIDGE_URL must use a loopback host.");
    const token = process.env.PUBLISH_BRIDGE_TOKEN?.trim(); if (!token) throw new Error("PUBLISH_BRIDGE_TOKEN is required.");
    const response = await this.fetcher(`${bridgeUrl().replace(/\/$/, "")}${path}`, { method: "POST", headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: JSON.stringify(body) });
    const payload = await response.json().catch(() => ({})) as Record<string, any>; return { response, payload };
  }
  async checkAuth(platform: PublishPlatformKey): Promise<AuthStatus> { try { const { response, payload } = await this.request("/auth/check", { platform }); return { ok: response.ok && payload.authenticated === true, status: payload.status || (response.ok ? "ready" : "failed"), message: payload.message || `${platform} authentication check completed.`, nextAction: payload.nextAction || "Inspect the platform session.", missingConfig: payload.missingConfig }; } catch(error) { return { ok: false, status: "pending_config", message: error instanceof Error ? error.message : "Bridge unavailable.", nextAction: "Start the local publish bridge." }; } }
  async publish(platform: PublishPlatformKey, payload: PlatformPublishPayload): Promise<PublishResult> { try { const { response, payload: value } = await this.request("/publish", { platform, ...payload }); return { ok: response.ok && value.ok !== false, status: value.status || (response.ok ? "pending_verify" : "failed"), mode: "real", publishStatus: value.publishStatus, platformArticleId: value.platformArticleId, externalTaskId: value.externalTaskId, platformDraftId: value.platformDraftId, editorUrl: value.editorUrl, publicUrl: value.publicUrl, idempotencyKey: payload.idempotencyKey, publicUrlPending: value.publicUrlPending ?? !value.publicUrl, failureCode: value.failureCode, failureReason: value.failureReason || (!response.ok ? `Bridge HTTP ${response.status}` : undefined), nextAction: value.nextAction || "Verify the publish result before any retry.", diagnosticSummary: value.diagnosticSummary }; } catch(error) { return { ok: false, status: "pending_verify", mode: "real", publishStatus: "failed", idempotencyKey: payload.idempotencyKey, publicUrlPending: true, failureCode: "publish_action_unconfirmed", failureReason: error instanceof Error ? error.message : "Bridge call failed.", nextAction: "Verify the platform; do not publish again blindly." }; } }
  async verify(platform: PublishPlatformKey, result: PublishResult): Promise<VerifyResult> { try { const { response, payload } = await this.request("/publish/verify", { platform, idempotencyKey: result.idempotencyKey, platformArticleId: result.platformArticleId, externalTaskId: result.externalTaskId, publicUrl: result.publicUrl }); const status = payload.status || (response.ok ? "pending_verify" : "failed"); return { ok: response.ok && payload.ok !== false, status, publishStatus: payload.publishStatus, verifyStatus: ["published_verified", "public_observed", "stable_published"].includes(status) ? "verified" : ["pending_verify", "published_pending_url"].includes(status) ? "pending" : "failed", platformArticleId: payload.platformArticleId || result.platformArticleId, externalTaskId: payload.externalTaskId || result.externalTaskId, publicUrl: payload.publicUrl || result.publicUrl, publicUrlPending: payload.publicUrlPending ?? !payload.publicUrl, failureCode: payload.failureCode, failureReason: payload.failureReason, nextAction: payload.nextAction || "Verification completed." }; } catch(error) { return { ok: false, status: "pending_verify", verifyStatus: "pending", platformArticleId: result.platformArticleId, externalTaskId: result.externalTaskId, publicUrl: result.publicUrl, publicUrlPending: true, failureCode: "verification_failed", failureReason: error instanceof Error ? error.message : "Verification failed.", nextAction: "Restore the bridge and retry verification only." }; } }
}

let defaultTransport: FormalPublishTransport = new BridgeTransport();
export function getDefaultTransport() { return defaultTransport; }
export function setDefaultTransport(transport: FormalPublishTransport) { defaultTransport = transport; }
